config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'horarios#principal'
  resources :employees
  resources :calendar
  resources :horarios, except: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :employees
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :type_register
end

app/models/type_register.rb
class TypeRegister < ApplicationRecord
  has_many :records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
    def index
    end
end
  

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  


  def index
    @employees = Employee.all
  end


  def new
    @employee = Employee.new
  end

  def edit
  end



  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @employee.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @employee.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end


  def destroy
    @employee.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
      def set_employee
        @employee = Employee.find(params[:id])
      end

      def employee_params
        params.require(:employee).permit(:nombre, :apellido, :celular)
      end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
    before_action :set_horario, only: [:edit, :update, :destroy, :show]
    before_action :set_employees, only: [:new, :edit, :create]
    def index
        @horarios = Horario.all
    end

    def new
      @horario = Horario.new
    end

    def show 
    end

    def edit
    end

    def create
        @horario = Horario.new(horario_params)
        respond_to do |format|
          if @horario.save
            format.json {head :no_content}
            format.js
          else
            debugger
            format.json { render json: @horario.errors.full_messages, status: :unprocessable_entity }
            format.js { render :new }
          end
        end
    end

    def update
        respond_to do |format|
          if @horario.update(horario_params)
            format.json { head :no_content }
            format.js
          else
            format.json { render json: @horario.errors.full_messages, status: :unprocessable_entity }
            format.js { render :edit }
          end
        end
    end

    def destroy
        @horario.destroy
        respond_to do |format|
          format.json { head :no_content }
          format.js
        end
    end
    
    private
    def horario_params
        params.require(:horario).permit(:hora, :estado, :employee_id)
    end

    def set_horario
        @horario = Horaio.find(params[:id])
    end
    
    def set_employees
        @employees = Employee.all
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/calendar/index.html.erb
<br><br><br><br><br>
<%= month_calendar do |date| %>
    <%= date %>
  <% end %>

app/views/employees/_form.html.erb
<%= form_for @employee, remote: true do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos del empleado:</h4>
  </div>

  <div class="item form-group<%= @employee.errors[:nombre].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :nombre, "Nombre del Empleado: " %>
    <div class="input-group">
      <%= f.text_field :nombre, {:class=> "form-control", :placeholder=>"Introduzca el nombre del empleado..."} %>
      <%if @employee.errors[:nombre].any? %>
        <p class="bg-danger"><%= @employee.errors[:nombre].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:apellido].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :apellido, "Apellido del Empleado: " %>
    <div class="input-group">
      <%= f.text_field :apellido, {:class=> "form-control", :placeholder=>"Introduzca el apellido del empleado..."} %>
      <%if @employee.errors[:apellido].any? %>
        <p class="bg-danger"><%= @employee.errors[:apellido].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @employee.errors[:celular].any? ? ' has-error has-feedback' : '' %>">
    <%= f.label :celular, "Celular del empleado: " %>
    <div class="input-group">
      <%= f.text_field :celular, {class: "form-control", :placeholder=>"Introduzca su numero de celular..."} %>
      <%if @employee.errors[:celular].any? %>
        <p class="bg-danger"><%= @employee.errors[:celular].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @employee.new_record? ? "Crear Empleado" : "Actualizar Empleado", :class => "btn btn-success"%>
  </div>
<% end %>

app/views/employees/_modal_employees.html.erb
<!-- Modal -->
<div class="modal fade" id="modalEmployees" tabindex="-1" role="dialog" aria-labelledby="modalEmployeesLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-employees-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-employees modal-body" id="modal-body-employees">

      </div>
      <div class="modal-footer" id="modal-footer-employees">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/employees/create.js.erb
$('#modalEmployees').modal('toggle');
$('#tablaEmployees').append(
    '<tr id="employee_<%= @employee.id %>" ><td><%= @employee.nombre %></td><td><%= @employee.apellido %></td><td><%= @employee.celular %></td><td><%= link_to 'editar', edit_employee_path(@employee), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @employee, remote: true, method: :delete, data: { confirm: "¿Borrar employee: #{@employee.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/employees/destroy.js.erb
$('#employee_<%= @employee.id %>').fadeOut();

app/views/employees/edit.js.erb
$('#modal-employees-title').html("Editar empleado");

$('.modal-body-employees').html('<%= j render("form") %>');

$('#modalEmployees').modal("show");

app/views/employees/index.html.erb
<h1 class="h2 mb-2 text-blue-900" style="margin-block: 110px;">Empleados </h1>

<div >
  <%= link_to new_employee_path, {remote: true, class: "btn btn-info", id: "anadir-employee-btn"} do %>
    <span class="fas fa-plus-square"></span>
    <%end%>
</div>

<div class="card shadow mb-4" style="width :80%; margin-left: 140px;">
  <div class="card-body">
    <div class="table-responsive" >
      <table id="tablaEmployees" class="table" width="100%"
        <thead class="table-info">
          <tr class="table-info">
            <th>Nombre Empleado</th>
            <th>Apellido Empleado</th>
            <th>Celular Empleado</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% Employee.all.each do |empl| %>
            <tr id="employee_<%= empl.id %>" >
              <td><%= empl.nombre %></td>
              <td><%= empl.apellido %></td>
              <td><%= empl.celular %></td>
              <td>
              <%= link_to "Editar", edit_employee_path(empl), html_options = {class: "btn btn-info btn-xs", remote: true} %>
              <%= link_to 'Borrar', empl, remote: true, method: :delete, data: { confirm: "¿Borrar employee: #{empl.nombre}?"}, class: "btn btn-danger btn-xs" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_employees' %>

app/views/employees/new.js.erb
// Add the dialog titlle
$('#modal-employees-title').html("Nuevo empleado");

// Render the new form
$('#modal-body-employees').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalEmployees').modal("show");

app/views/employees/update.js.erb
$('#modalEmployees').modal('toggle');
$('#employee_<%= @employee.id %>').replaceWith(
    '<tr id="employee_<%= @employee.id %>" ><td><%= @employee.nombre %></td><td><%= @employee.apellido %></td><td><%= @employee.celular %></td><td><%= link_to 'editar', edit_employee_path(@employee), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to "Borrar", @employee, remote: true, method: :delete, data: { confirm: "¿Borrar employee: #{@employee.nombre}?"}, class: "btn btn-danger btn-xs" %></td></tr>'
);

app/views/home/index.html.erb
<h1><br></h1>
<!-- Contact Section-->
        <section class="page-section" id="sistema">
            <div class="container">
                <!-- Contact Section Heading-->
                <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Sistema de Ingreso y Salida</h2>
                <!-- Icon Divider-->
                <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Contact Section Form-->
                <div class="row justify-content-center">
                    <div class="col-lg-8 col-xl-7">
                        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <!-- Name input-->
                            <label for="name">Ingrese su ID</label> 
                            <div class="form-floating mb-3">
                                
                                <input class="form-control" id="name" type="text" data-sb-validations="required" />
                                
                                <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                            </div>

                            <!-- Date number input-->
                            <div class="form-floating mb-3">
                                <input class="form-control" id="date" type="date" />
                                <div class="input-group date">
                                
                            </div>
                            <!-- IngresoSalida input-->
                            <div class="form-floating mb-3">
                              <br>
                              <select id="inputState" class="form-select">
                                <option></option>
                                <option>Ingreso...</option>
                                <option>Salida...</option>
                              </select>
                            </div>

                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            <!-- Submit Button-->
                            <button class="btn btn-primary btn-xl disabled" id="submitButton" type="submit">Send</button>
                        </form>
                    </div>
                </div>
            </div>
        </section>

app/views/horarios/_form.html.erb
<!-- Contact Section Form-->
    <div class="row justify-content-center">
        <div class="col-lg-8 col-xl-7">
            <%= form_for @horario, remote: true do |f| %>
                <!-- Empleado input-->
                    <div class="item form-group<%= @horario.errors[:employee].any? ? ' has-error has-feedback' : '' %>">
                        <%= f.label :employee, "Empleado: " %>
                            <div class="input-group">
                                <%= collection_select(:horario, :employees_id, @employees, :id, :id, {:prompt => 'Seleccione empleado'}, { class: "form-control" })%>
                                    <%if @horario.errors[:employee].any? %>
                            <p class="bg-danger"><%= @horario.errors[:employee].to_s[/\w([^"]*)/] %></p>
                        <% end %>
                    </div>

                <!-- IngresoSalida input-->
                    <br>
                    <div class="item form-group<%= @horario.errors[:estado].any? ? ' has-error has-feedback' : '' %>">
                        <%= f.label :estado, "Entrada o Salida: " %>
                            <div class="input-group" >
                                <%= f.select :estado, {:""=> "" , :Entrada=> "Entrada", :Salida=>"Salida"}%> 
                                    <%if @horario.errors[:estado].any? %>
                                <p class="bg-danger"><%= @horario.errors[:estado].to_s[/\w([^"]*)/] %></p>
                        <% end %>
                    </div>

                <!-- Hora input-->
                    <br>
                    <div class="item form-group<%= @horario.errors[:hora].any? ? ' has-error has-feedback' : '' %>">
                        <%= f.label :hora, "Ingrese fecha: " %>
                            <div class="input-group">
                                <%= f.datetime_field :hora, {:class=> "form-control", :placeholder=>"Ingrese fecha..."} %>        
                                    <%if @horario.errors[:hora].any? %>
                                <p class="bg-danger"><%= @horario.errors[:hora].to_s[/\w([^"]*)/] %></p>
                        <% end %>
                    </div>
                    

                </div>
                <br>
                <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                    <%= f.submit @horario.new_record? ? "Registrar Horario" : "Actualizar Horario", :class => "btn btn-success"%>
                </div> 
            <% end %>
                        
        </div>
    </div>
    

app/views/horarios/_modal_horarios.html.erb
<div class="modal fade" id="modalHorarios" tabindex="-1" role="dialog" aria-labelledby="modalHorariosLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-horarios-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-horarios modal-body" id="modal-body-horarios">

      </div>
      <div class="modal-footer" id="modal-footer-horarios">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/horarios/create.js.erb
$('#modalHorarios').modal('toggle');
$('#tablaHorarios').append(
    '<tr id="horario_<%= @horario.id %>" > <td><%= @horario.hora %></td><td><%= @horario.estado %></td> <td><%= @horario.employee != nil ? @product.employee.nombre : "No tiene empleado" %></td>'
);

app/views/horarios/index.html.erb
<br><br><br><br><br>
<h1 class="h3 mb-2 text-gray-800">Horarios</h1>
<div>  
                        <%= link_to new_horario_path, { remote: true, class: "btn btn-info" }  do %>
                            <span class="fas fa-plus-square" ></span>
                        <% end %>
                    </div>
<br />
<div class="card shadow mb-4">
<div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="tablaHorarios" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th></th>
            <th>Hora</th>
            <th>Estado</th>
            <th>Empleado</th>
        </tr>
        </thead>
        <tbody>
            <% @horarios.each do |hor| %>
            <tr id="horario_<%= hor.id %>" >
                <td><%= hor.hora %></td>
                <td><%= hor.estado %></td>
                <td><%= hor.employee != nil ? hor.employee.nombre : "No tiene empleado" %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    </div>
  </div>
</div>
<%= render 'modal_horarios' %>

app/views/horarios/new.js.erb
$('#modal-horarios-title').html("Crear horario");

$('.modal-body-horarios').html('<%= j render("form") %>');
 
$('#modalHorarios').modal("show");

app/views/horarios/principal.html.erb
<br><br><br><br>

<!-- Contact Section-->
<section class="page-section" id="sistema">
    <div class="container">
        <!-- Contact Section Heading-->
            <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Sistema de Ingreso y Salida</h2>
            <!-- Icon Divider-->
            <div class="divider-custom">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <div class="row justify-content-center">
                <div class="col-lg-8 col-xl-7">
                    <h1 class="h3 mb-2 text-gray-800">Ingrese su registro de horario</h1>
                    <div>  
                        <%= link_to new_horario_path, { remote: true, class: "btn btn-info" }  do %>
                            <span class="fas fa-plus-square" ></span>
                        <% end %>
                    </div>
                </div>
            </div>
    </div>
</section>

<%= render 'modal_horarios' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geosatelital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" media="all" href="/assets/styles.self-79ad96490916d5eb8129d3e9fa2307ba091433581e26b73d06b4b5e934e6f1f1.css?body=1" data-turbolinks-track="reload" />
    <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        
    </head>
    
  <body id="page-top">



    <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">Geosatelital</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#sistema">sistema</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#">Empleados</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#">Reporte</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="">Login</a></li>
                        <li class="nav-item mx-0 mx-lg-1"></li>
                        <%= link_to destroy_user_session_path, method: :delete, html_options: { class: "nav-item mx-0 mx-lg-1"}  do %>
                        <i class="nav-link py-3 px-0 px-lg-3 rounded" ></i>
                        Logout
                        <%end%>
                    </ul>
                </div>
            </div>
        </nav>

<%= yield%>
                <!-- Footer-->
                        <footer class="footer text-center">
                            <div class="container">
                                <div class="row">
                                    <!-- Footer Location-->
                                    <div class="col-lg-4 mb-5 mb-lg-0">
                                        <h4 class="text-uppercase mb-4">Ubicacion</h4>
                                        <p class="lead mb-0">
                                            direcion de la empresa
                                            <br />
                                            calle de la empresa
                                        </p>
                                    </div>
                                    <!-- Footer Social Icons-->
                                    <div class="col-lg-4 mb-5 mb-lg-0">
                                        <h4 class="text-uppercase mb-4">sitio web de la empresa</h4>
                                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>

                                    </div>
                                    <!-- Footer About Text-->
                                    <div class="col-lg-4">
                                        <h4 class="text-uppercase mb-4">descripcion</h4>
                                        <p class="lead mb-0">
                                            descripcion
                                            .
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </footer>


  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Geosatelital</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    
  <link rel="stylesheet" media="all" href="/assets/login.self-6c207500cddcaec560d3ea3471d3bf8d5af9de1ec297367e0d9167861ab6694d.css?body=1" data-turbolinks-track="reload" />
  
  </head>
<!--Coded with love by Mutiullah Samim-->
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">

        <%= yield %>

			</div>
		</div>
	</div>
</body>
</html>